server:
  port: 8000

spring:
  application:
    name: ms-listener

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mq:
  queues:
    example-queue: example-queue